
/**
 * Authorization
 */
DROP TABLE IF EXISTS `SYS_USER`;
CREATE TABLE SYS_USER(
	`id` BIGINT(20) NOT NULL AUTO_INCREMENT,
	`user_name` VARCHAR(30) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '用户名',
	`password` VARCHAR(32) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '密码',
	PRIMARY KEY  (`ID`)
) ENGINE=INNODB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;

INSERT INTO SYS_USER(USER_NAME,PASSWORD) VALUES('admin','21232f297a57a5a743894a0e4a801fc3');
INSERT INTO sys_user(`user_name`,`password`) VALUES('test','c4ca4238a0b923820dcc509a6f75849b'); 

/**
 * Role
 */
DROP TABLE IF EXISTS `SYS_ROLE`;
CREATE TABLE SYS_ROLE(
	`id` BIGINT(20) NOT NULL AUTO_INCREMENT,
	`role_name` VARCHAR(30) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '角色名',
	PRIMARY KEY  (`ID`)
) ENGINE=INNODB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;

INSERT INTO SYS_ROLE(ROLE_NAME) VALUES('ROLE_USER');
INSERT INTO SYS_ROLE(ROLE_NAME) VALUES('ROLE_ADMIN');
INSERT INTO SYS_ROLE(ROLE_NAME) VALUES('ROLE_ANONYMOUS');

/**
 * USER_ROLE_RELATION
 */
DROP TABLE IF EXISTS `SYS_USER_ROLE`;
CREATE TABLE SYS_USER_ROLE(
	`id` BIGINT(20) NOT NULL AUTO_INCREMENT,
	`user_id` VARCHAR(30) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '用户ID',
	`role_id` VARCHAR(30) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '角色ID',
	PRIMARY KEY  (`ID`)
) ENGINE=INNODB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;

INSERT INTO SYS_USER_ROLE(USER_ID,ROLE_ID) VALUES((SELECT ID FROM SYS_USER WHERE USER_NAME='admin'),(SELECT ID FROM SYS_ROLE WHERE ROLE_NAME='ROLE_USER'));
INSERT INTO SYS_USER_ROLE(USER_ID,ROLE_ID) VALUES((SELECT ID FROM SYS_USER WHERE USER_NAME='test'),(SELECT ID FROM SYS_ROLE WHERE ROLE_NAME='ROLE_USER'));


DROP TABLE IF EXISTS `t_xinwen`;
CREATE TABLE t_xinwen(
	`f_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
	`f_title` VARCHAR(30) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '用户ID',
	`f_content` VARCHAR(30) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '角色ID',
	`f_operate_date` DATETIME DEFAULT NULL COMMENT '创建时间',
	PRIMARY KEY  (`f_id`)
) ENGINE=INNODB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `t_common_message`;
CREATE TABLE t_common_message(
	`f_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
	`f_notify` VARCHAR(500) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '用户ID',
	`f_status` TINYINT(1) COLLATE utf8_unicode_ci DEFAULT 0 COMMENT '是否可用',
	`f_operate_date` DATETIME DEFAULT NULL COMMENT '创建时间',
	PRIMARY KEY  (`f_id`)
) ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;


DROP TABLE IF EXISTS `t_tiezi`;
CREATE TABLE `t_tiezi`(
	`f_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
	`f_user` VARCHAR(500) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '会员ID',
	`f_title` VARCHAR(500) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '用户ID',
	`f_content` VARCHAR(500) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '用户ID',
	`f_operate_date` DATETIME DEFAULT NULL COMMENT '创建时间',
	PRIMARY KEY  (`f_id`)
) ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;


DROP TABLE IF EXISTS `t_huifu`;
CREATE TABLE `t_huifu`(
	`f_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
	`f_tiezi_id` bigint(32) COLLATE utf8_unicode_ci DEFAULT 0 COMMENT '会员ID',
	`f_user` VARCHAR(500) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '会员ID',
	`f_content` VARCHAR(500) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '用户ID',
	`f_operate_date` DATETIME DEFAULT NULL COMMENT '创建时间',
	PRIMARY KEY  (`f_id`)
) ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;


DROP TABLE IF EXISTS `t_toupiao`;
CREATE TABLE `t_toupiao`(
	`f_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
	`f_username` VARCHAR(500) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '会员ID',
	`f_count` bigint(32) COLLATE utf8_unicode_ci DEFAULT 0 COMMENT '用户ID',
	`f_operate_date` DATETIME DEFAULT NULL COMMENT '创建时间',
	PRIMARY KEY  (`f_id`)
) ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;
