
/**
 * Authorization
 */
DROP TABLE IF EXISTS `SYS_USER`;
CREATE TABLE SYS_USER(
	`id` BIGINT(20) NOT NULL AUTO_INCREMENT,
	`user_name` VARCHAR(30) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '用户名',
	`password` VARCHAR(32) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '密码',
	PRIMARY KEY  (`ID`)
) ENGINE=INNODB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;

INSERT INTO SYS_USER(USER_NAME,PASSWORD) VALUES('admin','21232f297a57a5a743894a0e4a801fc3');

/**
 * Role
 */
DROP TABLE IF EXISTS `SYS_ROLE`;
CREATE TABLE SYS_ROLE(
	`id` BIGINT(20) NOT NULL AUTO_INCREMENT,
	`role_name` VARCHAR(30) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '角色名',
	PRIMARY KEY  (`ID`)
) ENGINE=INNODB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;

INSERT INTO SYS_ROLE(ROLE_NAME) VALUES('ROLE_ADMIN');
INSERT INTO SYS_ROLE(ROLE_NAME) VALUES('ROLE_ANONYMOUS');

/**
 * USER_ROLE_RELATION
 */
DROP TABLE IF EXISTS `SYS_USER_ROLE`;
CREATE TABLE SYS_USER_ROLE(
	`id` BIGINT(20) NOT NULL AUTO_INCREMENT,
	`user_id` VARCHAR(30) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '用户ID',
	`role_id` VARCHAR(30) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '角色ID',
	PRIMARY KEY  (`ID`)
) ENGINE=INNODB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;

INSERT INTO SYS_USER_ROLE(USER_ID,ROLE_ID) VALUES((SELECT ID FROM SYS_USER WHERE USER_NAME='admin'),(SELECT ID FROM SYS_ROLE WHERE ROLE_NAME='ROLE_ADMIN'));
